--liquibase formatted sql

--changeset frank:0 dbms:mssql
CREATE TABLE GLD.DIM_CONTINENT (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  TX_ES NVARCHAR(20) NOT NULL UNIQUE,
  TX_CA NVARCHAR(20) NOT NULL UNIQUE,
  TX_EN NVARCHAR(20) NOT NULL UNIQUE,
  TX_INE_ES NVARCHAR(20) UNIQUE,
  TX_ONU_ES NVARCHAR(20) UNIQUE,
);
--rollback DROP TABLE GLD.DIM_CONTINENT;

--changeset frank:1 dbms:mssql
CREATE TABLE GLD.DIM_INE_REGION (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  TX_ES NVARCHAR(50) NOT NULL UNIQUE,
  ID_CONTINENT INT NOT NULL,
  FOREIGN KEY (ID_CONTINENT) REFERENCES DIM_CONTINENT(ID)
);
--rollback DROP TABLE GLD.DIM_INE_REGION;

--changeset frank:2 dbms:mssql
CREATE TABLE GLD.DIM_ONU_REGION (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  TX_ES NVARCHAR(50) NOT NULL UNIQUE,
  ID_CONTINENT INT NOT NULL,
  FOREIGN KEY (ID_CONTINENT) REFERENCES DIM_CONTINENT(ID)
);
--rollback DROP TABLE GLD.DIM_ONU_REGION;

--changeset frank:3 dbms:mssql
CREATE TABLE GLD.DIM_ONU_SUBREGION (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  TX_ES NVARCHAR(50) NOT NULL UNIQUE,
  ID_REGION INT NOT NULL,
  FOREIGN KEY (ID_REGION) REFERENCES DIM_ONU_REGION(ID)
);
--rollback DROP TABLE GLD.DIM_ONU_SUBREGION;

--changeset frank:4 dbms:mssql
CREATE TABLE GLD.DIM_COUNTRY (
  ID INT IDENTITY(1,1) PRIMARY KEY,
  CO_ISO3166_1_ALPHA2 CHAR(2) NOT NULL UNIQUE,
  CO_ISO3166_1_ALPHA3 CHAR(3) NOT NULL UNIQUE,
  CO_ISO3166_1_NUMERIC CHAR(3) NOT NULL UNIQUE,
  CO_INE INT NOT NULL,
  TX_ES NVARCHAR(50) NOT NULL UNIQUE,
  TX_CA NVARCHAR(50) NOT NULL UNIQUE,
  TX_EN NVARCHAR(50) NOT NULL UNIQUE,
  ID_INE_REGION INT NOT NULL,
  ID_ONU_REGION INT NOT NULL,
  ID_ONU_SUBREGION INT,
  FOREIGN KEY (ID_INE_REGION) REFERENCES DIM_INE_REGION(ID),
  FOREIGN KEY (ID_ONU_REGION) REFERENCES DIM_ONU_REGION(ID),
  FOREIGN KEY (ID_ONU_SUBREGION) REFERENCES DIM_ONU_SUBREGION(ID)
);
--rollback DROP TABLE GLD.DIM_COUNTRY;
